// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa6ddPnk4BGyXxt39brUUW2cfm4Fp7qyQ',
    appId: '1:846332997606:web:9318151b2c8d58b13cf027',
    messagingSenderId: '846332997606',
    projectId: 'mvp-one-ec85c',
    authDomain: 'mvp-one-ec85c.firebaseapp.com',
    storageBucket: 'mvp-one-ec85c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ikMT79YK8Co5_zGGTrSmypHqnvrY7Qw',
    appId: '1:846332997606:android:3c4aa30a504d20d83cf027',
    messagingSenderId: '846332997606',
    projectId: 'mvp-one-ec85c',
    storageBucket: 'mvp-one-ec85c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMPK-X9PfKpqFwjxCmOga8d6xJ3BOVwk',
    appId: '1:846332997606:ios:db67297f13f205423cf027',
    messagingSenderId: '846332997606',
    projectId: 'mvp-one-ec85c',
    storageBucket: 'mvp-one-ec85c.appspot.com',
    iosBundleId: 'com.example.mvpOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxMPK-X9PfKpqFwjxCmOga8d6xJ3BOVwk',
    appId: '1:846332997606:ios:d74db4aa0fd0debd3cf027',
    messagingSenderId: '846332997606',
    projectId: 'mvp-one-ec85c',
    storageBucket: 'mvp-one-ec85c.appspot.com',
    iosBundleId: 'com.example.mvpOne.RunnerTests',
  );
}
