// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBbHgLQabaODCk9RbsrNzPON1cz0ald4',
    appId: '1:822511194843:web:81c9da1bb00786980e72fe',
    messagingSenderId: '822511194843',
    projectId: 'mvp-one',
    authDomain: 'mvp-one.firebaseapp.com',
    databaseURL: 'https://mvp-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mvp-one.appspot.com',
    measurementId: 'G-JET511WSQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrcz_zS4kTAtjOK1AQ4QheMePcaWeHpY',
    appId: '1:822511194843:android:76334a20ba426ec10e72fe',
    messagingSenderId: '822511194843',
    projectId: 'mvp-one',
    databaseURL: 'https://mvp-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mvp-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTZdSalOfUUQt4rq6sakPU4azkdFsE4I',
    appId: '1:822511194843:ios:10905c85df5a1c6a0e72fe',
    messagingSenderId: '822511194843',
    projectId: 'mvp-one',
    databaseURL: 'https://mvp-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mvp-one.appspot.com',
    iosClientId: '822511194843-lau4vmifiejev54h2mu6rr2nsqs2538r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvpOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTZdSalOfUUQt4rq6sakPU4azkdFsE4I',
    appId: '1:822511194843:ios:eb38df42b3f59e1b0e72fe',
    messagingSenderId: '822511194843',
    projectId: 'mvp-one',
    databaseURL: 'https://mvp-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mvp-one.appspot.com',
    iosClientId: '822511194843-l1nadonhvrlud53pm51ng4eiq8591ttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvpOne.RunnerTests',
  );
}
